{{ with .Values.deployments.api }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: openbalena
    component: api
  name: openbalena-api
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: openbalena
      component: api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openbalena
        component: api
    spec:
      containers:
      - image: {{ .image }}:{{ .version }}
        name: openbalena-api
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
            - SYS_RESOURCE
          privileged: true
        env:
        - name: CONFD_BACKEND
          value: "ENV"
        - name: API_VPN_SERVICE_API_KEY
          value: "{{ $.Values.keys.api_vpn_service_api_key }}"
        - name: BALENA_ROOT_CA
          value: "{{ $.Values.certificates.root.ca }}"
        - name: COOKIE_SESSION_SECRET
          value: "{{ $.Values.keys.cookie_secret }}"
        - name: DB_HOST
          value: "openbalena-db"
        - name: DB_PASSWORD
          value: "docker"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "docker"
        - name: DELTA_HOST
          value: "delta.{{ $.Values.hostname }}"
        - name: DEVICE_CONFIG_OPENVPN_CA
          value: "{{ $.Values.certificates.vpn.ca_chain }}"
        - name: DEVICE_CONFIG_SSH_AUTHORIZED_KEYS
          value: "{{ $.Values.config.ssh_authorized_keys }}"
        - name: HOST
          value: "{{ .ingress.subdomain }}.{{ $.Values.hostname }}"
        - name: IMAGE_MAKER_URL
          value: "img.{{ $.Values.hostname }}"
        - name: IMAGE_STORAGE_BUCKET
          value: "resin-production-img-cloudformation"
        - name: IMAGE_STORAGE_ENDPOINT
          value: "s3.amazonaws.com"
        - name: IMAGE_STORAGE_PREFIX
          value: "resinos"
        - name: JSON_WEB_TOKEN_EXPIRY_MINUTES
          value: "10080"
        - name: JSON_WEB_TOKEN_SECRET
          value: "{{ $.Values.keys.jwt_secret }}"
        - name: MIXPANEL_TOKEN
          value: "__unused__"
        - name: PRODUCTION_MODE
          value: "{{ $.Values.config.production_mode }}"
        - name: PUBNUB_PUBLISH_KEY
          value: "__unused__"
        - name: PUBNUB_SUBSCRIBE_KEY
          value: "__unused__"
        - name: REDIS_HOST
          value: "{{ $.Values.deployments.redis.config.host }}"
        - name: REDIS_PORT
          value: "{{ $.Values.deployments.redis.config.port }}"
        - name: REGISTRY2_HOST
          value: "{{ $.Values.deployments.registry.ingress.subdomain }}.{{ $.Values.hostname }}"
        - name: REGISTRY_HOST
          value: "{{ $.Values.deployments.registry.ingress.subdomain }}.{{ $.Values.hostname }}"
        - name: SENTRY_DSN
          value: "{{ .sentry_dsn }}"
        - name: TOKEN_AUTH_BUILDER_TOKEN
          value: "{{ $.Values.keys.token_auth_builder_token }}"
        - name: TOKEN_AUTH_CERT_ISSUER
          value: "api.{{ $.Values.hostname }}"
        - name: TOKEN_AUTH_CERT_KEY
          value: "{{ $.Values.keys.token_auth_key }}"
        - name: TOKEN_AUTH_CERT_KID
          value: "{{ $.Values.keys.token_auth_kid }}"
        - name: TOKEN_AUTH_CERT_PUB
          value: "{{ $.Values.keys.token_auth_pub }}"
        - name: TOKEN_AUTH_JWT_ALGO
          value: "ES256"
        - name: VPN_HOST
          value: "{{ $.Values.deployments.vpn.ingress.subdomain }}.{{ $.Values.hostname }}"
        - name: VPN_PORT
          value: "{{ $.Values.deployments.vpn.ingress.port }}"
        - name: VPN_SERVICE_API_KEY
          value: "{{ $.Values.keys.service_api_key }}"
        - name: SUPERUSER_EMAIL
          value: "{{ $.Values.config.email }}"
        - name: SUPERUSER_PASSWORD
          value: "{{ $.Values.config.password }}"
        volumeMounts:
        - mountPath: /run
          name: openbalena-api-tmpfs0
        - mountPath: /sys/fs/cgroup
          name: openbalena-api-tmpfs1
      volumes:
      - emptyDir:
          medium: Memory
        name: openbalena-api-tmpfs0
      - emptyDir:
          medium: Memory
        name: openbalena-api-tmpfs1
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: openbalena
    component: api
  name: openbalena-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: openbalena
    component: api
status:
  loadBalancer: {}
{{- end }}
{{- end }}
