{{ with .Values.deployments.redis }}
{{- if .enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: openbalena
    component: redis
  name: openbalena-redis
spec:
  serviceName: openbalena-redis
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: openbalena
      component: redis
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openbalena
        component: redis
    spec:
      containers:
      - image: "{{ .image }}:{{ .version }}"
        name: openbalena-redis
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: openbalena-redis-volume
          subPath: redis
      volumes:
      - name: openbalena-redis-volume
        persistentVolumeClaim:
          claimName: openbalena-redis-volume
  volumeClaimTemplates:
  - metadata:
      name: openbalena-redis-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .volume.storage }}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: openbalena
    component: redis
  name: openbalena-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: {{ .config.port }}
  selector:
    app: openbalena
    component: redis
status:
  loadBalancer: {}
{{- end }}
{{- end }}
